### ISSUE TITLE
191r

### ISSUE THREAD

**Issue by ncchur** [HCMID/venA-15#4]
urn:cite:hmt:vaimg.VA191RN-0362@0.501,0.8062,0.035,0.015

Unidentified floating symbols above the word "φιλοσοφεῖ" 
scholia urn:cts:greekLit:tlg5026.msA.hmt:15.16

**Comment by StephanieML** [comment]
it looks like νῦν to me

**Comment by StephanieML** [comment]
side note, don't know if it's related at all to this scholion, but we did see νῦν floating over a quoted section before to indicate the present tense. I believe this was back in Book 2 of the Venetus A. So if the word νῦν doesn't make sense in context, that might be a possibility, though a minute one.

**Comment by arsimr16** [comment]
I added the word with a supralinear tag.
