### ISSUE TITLE
Validation not getting scholia in book 15

### ISSUE THREAD

**Issue by brclar15** [HCMID/venA-15#5]
:(

**Comment by StephanieML** [comment]
Hmmm, something in the inventory. I'll check it out and let you know when I've fixed it.

**Comment by brclar15** [comment]
cool cool, no real rush. There's plenty of editing to keep us busy

**Comment by StephanieML** [comment]
fixed

**Comment by StephanieML** [comment]
make sure you pull

**Comment by brclar15** [comment]
wow you're so good!

**Comment by StephanieML** [comment]
I'm magic
