### ISSUE TITLE
Indiscernible Supralinear Ligature 199v

### ISSUE THREAD

**Issue by cshanley18** [HCMID/venA-15#9]
urn:cts:greekLit:tlg0012.tlg001.msA:15.444

Within the scholion, there is an unclear supralinear above the second "ό" in the word ξεινοδόκον.  It appears to be a deleted ligature for "ω," but we were unsure of how to mark this.  We used an "orig"/"reg" tag around the word, and then set a "del" tag around the entire regularized form.  We did this because it seems that the deletion of the ligature implies the deletion of the whole multiform.  

urn:cite:hmt:vaimg.VA199VN-0701@0.24,0.5477,0.083,0.0218

**Comment by StephanieML** [comment]
i agree with your markup, but I think it was just once an omega, not a ligature for omega, or an abbreviation, if that's what you meant.

**Comment by brclar15** [comment]
.... so the end result would be the same, right? if it were a written omega vs the squiggle that stands for omega, either way, we're good?

**Comment by StephanieML** [comment]
yes
